spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://54.180.69.255:3306/poc
      username: swa
      password: swa1234#
    url: jdbc:mariadb://54.180.69.255:3306/poc
    username: swa
    password: swa1234#
    driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: UTF-8
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
  session:
    store-type: redis
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  freemarker:
    cache: false

logging:
  level:
    root: info




mybatis:
  #type-aliases-package: com.lgcns.BootPoc.template.hello.repository
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true